// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE2I8ejRmpC-dRGC9bqlJT__5UmPm4kGE',
    appId: '1:587499801358:web:955bcc12128f2b5c3d255f',
    messagingSenderId: '587499801358',
    projectId: 'fir-a-to-z',
    authDomain: 'fir-a-to-z.firebaseapp.com',
    storageBucket: 'fir-a-to-z.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_g8ZO6Cjb-z1mWy4P7kNvX0qG9Nsdeu0',
    appId: '1:587499801358:android:7678d516d71f58993d255f',
    messagingSenderId: '587499801358',
    projectId: 'fir-a-to-z',
    storageBucket: 'fir-a-to-z.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAddLn03Yx70FSl1Hr326DSJ9RcaRwcFCI',
    appId: '1:587499801358:ios:33cee0c4bdbe89853d255f',
    messagingSenderId: '587499801358',
    projectId: 'fir-a-to-z',
    storageBucket: 'fir-a-to-z.appspot.com',
    iosClientId: '587499801358-omnh909lqc2ktpiocm0ju294hgp6hr6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseUserdbTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAddLn03Yx70FSl1Hr326DSJ9RcaRwcFCI',
    appId: '1:587499801358:ios:c826d3800b9d53123d255f',
    messagingSenderId: '587499801358',
    projectId: 'fir-a-to-z',
    storageBucket: 'fir-a-to-z.appspot.com',
    iosClientId: '587499801358-eat8r2qp87umrkjf9tat1neoh896ad65.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseUserdbTask.RunnerTests',
  );
}
